### ISSUE TITLE
Not working on Mac OS?

### ISSUE THREAD

**Issue by majoess** [SkaceKamen/vscode-sqflint#10]
Hello,

on my Mac the SQFLint extension don't work. Actually nothing. It this 'expected' or not? 
My version: macOS Sierra 10.12.3 (no hackintosh, original)

**Comment by SkaceKamen** [comment]
It's possible, I never tested it. This extension uses java parser at background, do you have some form of JVM installed?

**Comment by majoess** [comment]
Thanks for the fast answer. On my PC (Windows) it's working. Btw. great extension - I really love it!

I already have Java installed, I will try this again with Java SE (JRE?)

**Comment by majoess** [comment]
I actually don't know, are there any error logs of Visual Studio Code?

**Comment by SkaceKamen** [comment]
Is java executable in your PATH? (can you just open console and write java to check?). The extension currently doesn't try to search for it or anything, just assumes there is "java" in path, so this may be issue.

**Comment by majoess** [comment]
miro@donttouchme:~$ java -version
  java version "1.8.0_121"
  Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
  miro@donttouchme:~$

**Comment by SkaceKamen** [comment]
So java is fine. I need to look to the VS output.
Open some SQF file, then open Output (View > Output). Then, in the top right corner of the Output, select SQF Language Server.
You should then see extension output, there sould be some clues about what went wrong.

**Comment by majoess** [comment]
There is actually nothing.

**Comment by SkaceKamen** [comment]
That's weird.
So it doesn't work at all? No syntax checking, no help for functions when you hover over then?
What happens when you open command palette ( CTRL + SHIFT + P ) and write SQF?

**Comment by majoess** [comment]
Again nothing

**Comment by SkaceKamen** [comment]
Welp, I'm cluless :sweat:.
Looks like the extension didn't even install or initialize. The command palette should at least list the extension commands ("SQF Commands list" for example), which are defined in the extension meta informations and aren't tied to any scripts.

**Comment by majoess** [comment]
I actually don't know, are there any error logs of Visual Studio Code?

**Comment by SkaceKamen** [comment]
So, do you have any other extensions installed? Do they work correctly?
If so, could you try uinstalling and installing the extension again, while having the Output opened?

**Comment by majoess** [comment]
Yes they do. Like SQF Language.

**Comment by SkaceKamen** [comment]
That's weird, I have no clue what can be causing this.

**Comment by HarryTRM** [comment]
That is an issue with your specific VSCode installation @majoess, it works fine for me. I can see the errors, it works perfectly. Try clearing your VSCode cache.
