### ISSUE TITLE
Absolute include paths

### ISSUE THREAD

**Issue by AsFoxy** [SkaceKamen/vscode-sqflint#11]
Are absolute include paths e.g. `#include "my\my_addon\my_file.h"` supported?

In my project source the corresponding path is `addons/my_addon/my_file.h`.
Is it possible to configure include path resolution to take this into account?

**Comment by SkaceKamen** [comment]
Solution already proposed here: https://github.com/SkaceKamen/vscode-sqflint/issues/9
It will probably be in next release, currently I was focused on fixing broken stuff.
