### ISSUE TITLE
Version 0.8 crash

### ISSUE THREAD

**Issue by Dorbedo** [SkaceKamen/vscode-sqflint#13]
SQFLint extension crashes after updating to Version 0.8

```
Indexing workspace...
SQFLint: Process crashed { Error: spawn java ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs: 
   [ '-jar',
     'C:\\Users\\Dorbedo\\.vscode\\extensions\\skacekachna.sqflint-0.8.0\\bin\\SQFLint.jar',
     '-j',
     '-v',
     '-s' ] }
(node:17708) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: write EPIPE
(node:17708) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
SQFLint: Process crashed with code -4058
```

**Comment by SkaceKamen** [comment]
Could you try running this?
```
java -jar C:\\Users\\Dorbedo\\.vscode\\extensions\\skacekachna.sqflint-0.8.0\\bin\\SQFLint.jar
```

**Comment by Dorbedo** [comment]
Thx, now it's working.

**Comment by SkaceKamen** [comment]
Heh, I just wanted to check what's causing the issue, this wasn't fix. I guess it was just random error when trying to launch java.

**Comment by Dorbedo** [comment]
It was working for a short period as intendet.
But now i have some troubles with your new feature again.

`#include "\test\macros.hpp"` with `"\\test\\" : "P:/testfolder/"` works fine
`#include "\x\cba\addons\main\script_macros_common.hpp"` with `"\\x\\": "P:/x/"` doesn't work

**Comment by SkaceKamen** [comment]
I'll look into it, that's weird

**Comment by SkaceKamen** [comment]
Ok, could you try to change the `"\\x\\": "P:/x/"` to `"\\x\\": "P:\\x\\"` ?
That should fix it, I will publish update which will fix this soon.

**Comment by Dorbedo** [comment]
I've done some testing:
It's not crashing because of the path, it seems to be crashing because of some definition inside of "script_macros_common.hpp".

**Comment by SkaceKamen** [comment]
Oh, i see the issue, there is #include "script_macros_common.hpp" in comments, so the parser gets stuck in infinite include loop. I need to fix the comments parsing.

**Comment by SkaceKamen** [comment]
Looks fixed, I'll publish update asap.

**Comment by SkaceKamen** [comment]
Version 0.8.1 should fix this issue.

**Comment by Dorbedo** [comment]
It works like a charm now.
Thanks for your great work.
