### ISSUE TITLE
try {} catch {}; statement is not supported yet

### ISSUE THREAD

**Issue by AGPHeaddikilla** [SkaceKamen/vscode-sqflint#2]
Hey,

recently i used this statement and it isnt syntax supported.
So these are the following syntax parts:
```sqf
try { ... } catch { ... };
```
and
```sqf
if ... throw <any>;
```
Just to notice it.

**Comment by SkaceKamen** [comment]
Completely forgot about this, I'll add it in next release.

**Comment by AGPHeaddikilla** [comment]
Thanks for your reply!

**Comment by SkaceKamen** [comment]
Should be fixed in v0.6.2.
