### ISSUE TITLE
CfgFunctions parser issue

### ISSUE THREAD

**Issue by Wyqer** [SkaceKamen/vscode-sqflint#20]
Reference: https://github.com/SkaceKamen/vscode-sqflint/issues/19#issuecomment-356000333

> But there is already parser for cfgFunctions in description.ext.

Hrm, then I guess it don't go some levels further down concerning includes.

In my current project it's structured that the description.ext includes a functions.hpp in the root folder. And that functions.hpp just fetches (via includes) the functions from other `functions.hpp` files which are inside seperate module folders. Guess some kind of comparable to the structure @TheMysteriousVincent mentioned.

Could it be possible that it just include one level further down from the description.ext but don't include further levels from that point?

**Comment by SkaceKamen** [comment]
It should work for multiple levels, I'll take a look.

**Comment by Wyqer** [comment]
Just as example for the structure:

This is the hpp which is called from the description.ext:
https://github.com/Wyqer/kp_liberation/blob/v0.97/Missionframework/KPLIB_functions.hpp

And that is including the module function files like this one:
https://github.com/Wyqer/kp_liberation/blob/v0.97/Missionframework/modules/00_init/functions.hpp

Alls defined functions were marked as "not defined" in the issues info at the bottom bar, so I added the function names in the `sqflint.ignoredVariables` to avoid that. It's fine so far, so don't worry. Just as we had the discussion in the other issue, I thought I could point on this. It's nothing critical :)

**Comment by SkaceKamen** [comment]
I just tried to create multi-level include and it works fine. I also tried files you mentioned and those worked fine too.

Do you have the mission opened as folder, or do you just edit individual files? (description.ext is only parsed when you're in folder mode)
When you open description.ext, do you see any errors? (there may be some issue with parser, if it fails to parse only single line of description.ext, nothing will be parsed)

**Comment by Wyqer** [comment]
I've opened it as folder, to have the project view, of course.
But maybe the "issue" is, that I don't open (reference to the Liberation repository) the `missionframework` folder to work. I open the `root` of the repository where the missionframework folder, the readme, etc. is located in. So as it works on your side it has to be an own fault obviously. So I guess that's the important thing which "breaks" the parser, as it has the wrong root folder in comparison to the fact that in the end the description.ext will be located in the mission root folder.

**Comment by SkaceKamen** [comment]
Oh, now it that makes sense!

I'll add some basic logic for finding description.ext in subfolders.

**Comment by Wyqer** [comment]
Ok, that would be indeed great and I guess it wouldn't much of work to reference the parser to the location where the description.ext is located.

Many thanks for your incredibly fast responses and very helpful attitude.

**Comment by SkaceKamen** [comment]
Should be fixed in 0.8.6
