### ISSUE TITLE
High CPU usage in VSCode 1.20.0

### ISSUE THREAD

**Issue by adampiskorski** [SkaceKamen/vscode-sqflint#22]
Hello

After I updated to VSCode 1.20.0, I get high CPU usage when not doing anything. If I only disable this extension and leave all others on (including SQF Language). 
The JVM is consuming the CPU usage.
![capture](https://user-images.githubusercontent.com/7703045/36202774-d4ec25f4-118d-11e8-9af9-a5e42056c534.PNG)
 I am on Windows 10 Pro x64 and my Java build is 1.8.0_161-b12.
My CPU is an i5 7600K overclocked to 4.8 GHz, so that you can get a sense of how intensive the bug is.

**Comment by SkaceKamen** [comment]
Could you try to disable workspace indexing? It's the `sqflint.indexWorkspace` (or something like this). Also if you open Output and select SQF extension, you can see if it's indexing workspace (which can have high CPU usage)

**Comment by adampiskorski** [comment]
Sorry for the delay.
So it is the indexing as it says so in the output and when I disable it using the setting you provided the CPU usage goes away.
However, this may still be a bug as, after several hours, the high CPU usage is still there.
The mission directory does not have so many lines that it would warrant such prolonged CPU usage IMO, though I could be wrong.
Here is the mission that would allow you to reproduce the bug: [ZAMF](https://github.com/zulu-alpha/ZAMF) and this mission is used as a template for all of our other missions, that we actually play.

**Comment by SkaceKamen** [comment]
Yea, there can be bug in indexing or perhaps some sqf file with unexpected combination of commands which can cause infinite loop.

I'll try to find what is causing it.

**Comment by SkaceKamen** [comment]
Probably fixed now.
