### ISSUE TITLE
Fails to recognize missing semicolon

### ISSUE THREAD

**Issue by dedmen** [SkaceKamen/vscode-sqflint#25]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_setActiveSwRadio.sqf#L23
works:
![code_2018-05-11_11-32-00](https://user-images.githubusercontent.com/3768165/39917817-fcb54344-550e-11e8-983c-e662727a11f4.png)
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/1.0/addons/core/functions/fnc_setActiveSwRadio.sqf#L25
doesn't work
![code_2018-05-11_11-32-46](https://user-images.githubusercontent.com/3768165/39917845-1083ddc2-550f-11e8-806c-c3cdc5791f4a.png)

**Comment by SkaceKamen** [comment]
Related to #35. I'll need to rework the grammar a bit.

**Comment by SkaceKamen** [comment]
Partially fixed in version 0.9.0

**Comment by dedmen** [comment]
Confirmed fix. Though
`Identifier(_old) and Identifier(TFAR_currentUnit) is not a valid combination of expressions` seems a little unclear. But it's still pretty obvious that the missing semicolon is the problem
