### ISSUE TITLE
Simple expression not supported

### ISSUE THREAD

**Issue by veteran29** [SkaceKamen/vscode-sqflint#28]
It seems that [Simple Expression](https://community.bistudio.com/wiki/Simple_Expression) in config files breaks the parser.

Example file: [KPLIB_playerOptions.hpp](https://github.com/SkaceKamen/vscode-sqflint/files/2099446/KPLIB_playerOptions.txt)

`min` in this expression is not supported:
```sqf
sizeEx = (((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1);
```

**Comment by SkaceKamen** [comment]
Didn't know the `min` is possible, will fix
