### ISSUE TITLE
problems with # and params

### ISSUE THREAD

**Issue by shukari** [SkaceKamen/vscode-sqflint#30]
Behind the "_group;" the error `Encountered ";". Was expecting one of: "=" ... ">" ..."` will be shown.

```
(disconnectCache # (_find # 0)) params ["_uid", "_group"];
	
[player] joinSilent _group;
```

**Comment by SkaceKamen** [comment]
What is the effect of `#` in SQF? I'm a bit confused.

**Comment by veteran29** [comment]
`#` was addeded some time ago. It works exactly like `select` but has higher operator precedence.

**Comment by SkaceKamen** [comment]
oh ... that's cool. Still, I wish they used `[]` as any other language
