### ISSUE TITLE
feature request: ignore var wildcards

### ISSUE THREAD

**Issue by shukari** [SkaceKamen/vscode-sqflint#31]
`"sqflint.ignoredVariables": ["ace_*"],`

to ignore all vars that start with "ace_"

**Comment by SkaceKamen** [comment]
Makes sense. I'll try to add it in future.

**Comment by Wyqer** [comment]
Could be handy for some people, of course.
On the other hand you don't recognize typos in the function names anymore, if you use any of the ace functions. Basically you loose a feature in my opinion. I'm not saying it shouldn't be implemented, everyone should have the possibility to use wildcards. Just a heads up for the OP.

**Comment by SkaceKamen** [comment]
Implemented in version 0.9.0
