### ISSUE TITLE
Empty classes in hpp files are not supported

### ISSUE THREAD

**Issue by hpy** [SkaceKamen/vscode-sqflint#32]
inside RscDefines.hpp file:
As an example:
![image](https://user-images.githubusercontent.com/13535616/43132540-7fed5616-8f7f-11e8-864b-ff95a0298c22.png)

Error thrown on first line at the semi colon:

[sqflint] Expected ":", "{", comment, end of line, or whitespace but ";" found.

**Comment by SkaceKamen** [comment]
Oh, you're right, I forgot about empty classes. I'll try to add it in future.
