### ISSUE TITLE
Wiki links in hints for functions are broken

### ISSUE THREAD

**Issue by Sparfell** [SkaceKamen/vscode-sqflint#34]
If you move the cursor over a function the link toward BI wiki is not functionnal. See screenshot below : 
https://i.imgur.com/nkzi55L.png?1

**Comment by SkaceKamen** [comment]
Yea that can happen, because the description is basically parsed bi wiki, so unexpected formatting can break the suggestion box.

You can post list of functions with this problem here, so I can update the parser accordingly.

**Comment by Sparfell** [comment]
Thanks for your answer.
In fact, I didn't find a function hint with a working link.
I tried a few functions from this page : 
https://community.bistudio.com/wiki/Category:Arma_3:_Functions
The following functions were tested and all have broken links : 
```
BIS_fnc_randomPosTrigger
BIS_fnc_dynamicText
BIS_fnc_spawnGroup
BIS_fnc_showAANArticle
BIS_fnc_findSafePos
BIS_fnc_setVehicleMass
BIS_fnc_endMission
BIS_fnc_showWelcomeScreen
BIS_fnc_spawnVehicle
BIS_fnc_getFactions
BIS_fnc_traceBullets
BIS_fnc_ORBATOpen
BIS_fnc_garage
BIS_fnc_carAlarm
BIS_fnc_curatorHint
BIS_fnc_setDate
BIS_fnc_isPosBlacklisted
```
Every links cuts after ".../wiki/BIS" as if the "_" between "BIS" and "fnc" was missing.

**Comment by SkaceKamen** [comment]
I'll look into it

**Comment by SkaceKamen** [comment]
Ok, so the issue is that having underscore in links, that are in italics breaks the markdown parser in vscode ... removing the italics seems to fix the issue.

I'll push update soon.

**Comment by Sparfell** [comment]
Thanks for your work. :)

**Comment by SkaceKamen** [comment]
Version 0.8.8 now has fixed links for functions and should also have some better docs.
