### ISSUE TITLE
if statement on variables

### ISSUE THREAD

**Issue by AGPHeaddikilla** [SkaceKamen/vscode-sqflint#4]
I've noticed the following:
If-Statement-Returns do not work on variables.
```sqf
private _foo = (if (true) then { false; } else { true; });
```

It would be nice, if you fix this.

**Comment by SkaceKamen** [comment]
I didn't know you can do this, I've rewritten the syntax checking code to allow more complex structures like this, so expect it to be fixed in next release.

**Comment by AGPHeaddikilla** [comment]
Thanks
