### ISSUE TITLE
Error using macros with arguments on other macros

### ISSUE THREAD

**Issue by ConnorAU** [SkaceKamen/vscode-sqflint#41]
If I use TEST on another macro and use that macro in script it says its incorrect.
![Image 1](https://user-images.githubusercontent.com/15099385/47893088-df793480-dea6-11e8-922f-5b846b43e998.png)
However using TEST directly in the script isnt a problem.
![Image 2](https://user-images.githubusercontent.com/15099385/47893197-75ad5a80-dea7-11e8-8e17-9497acb4add4.png)

**Comment by SkaceKamen** [comment]
Damn macros, never working properly :'(

**Comment by SkaceKamen** [comment]
Fixed in 0.9.6
