### ISSUE TITLE
Using macro with argument twice in same line causes error

### ISSUE THREAD

**Issue by ConnorAU** [SkaceKamen/vscode-sqflint#43]
![Example](https://user-images.githubusercontent.com/15099385/47971037-c0fa7f80-e0d8-11e8-9987-e6de9b2e14ed.png)
![Errors](https://user-images.githubusercontent.com/15099385/47971039-c5269d00-e0d8-11e8-8f17-63b9e8b40dc2.png)

**Comment by SkaceKamen** [comment]
Fixed in 0.9.7, sorry for delay
