### ISSUE TITLE
includePrefixes seems to work only in sqf and not in hpp files

### ISSUE THREAD

**Issue by DerZade** [SkaceKamen/vscode-sqflint#45]
I configured the `includePrefixes` in the settings to recognize the unzipped cba code on my P drive:
```json
"sqflint.includePrefixes": {
    "\\x\\cba\\": "P:/x/cba/"
}
```
This seems to work fine when I include the main script macros in a sqf file:
```#include "\x\cba\addons\main\script_macros.hpp"```
but doesn't work when included in a _Arma header file_ (`.hpp` for example)

**Comment by SkaceKamen** [comment]
I guess the issue happens with files that are sourced from `description.ext`?

**Comment by DerZade** [comment]
I don't know about `description.ext`. I was trying to setup a workspace for our mod which has a similar structure as ACE or CBA, so all paths to the pbos start with `\x\...` (or `\z\`) and we use the CBA macros which are included by a so-called `script_component`. All functions include the pbo specific `script_component`, which works just fine, because those are relative paths and it's in a sqf file, but that pbo specific `script_component` usually includes the `script_component` from the main pbo, which won't work because the path starts with `\x\..` and the `includePrefixes` doesn't seem to work in Arma header files.

Take the following example, which won't work:
https://github.com/acemod/ACE3/blob/master/addons/arsenal/script_component.hpp#L3

Agian: Everything with `includePrefixes` works fine in sqf files, but not in a header file.

**Comment by SkaceKamen** [comment]
ok, thanks for clarification - I was asking because there are two types of hpp files, one that uses description.ext syntax (`class hlbasla {}`) and other being just sqf import. Seems like the issue is with both.

**Comment by CarloDePieri** [comment]
Any news on this issue? I, as well, would love for sqflint to handle includePrefix correctly
