### ISSUE TITLE
Java constantly occupies 25...50% of CPU if plugin is enabled

### ISSUE THREAD

**Issue by Sparker95** [SkaceKamen/vscode-sqflint#49]
Hi!

For some reason it takes too much of my CPU when I open my project, which is a folder with lots of .sqf files.
I've let it run for half an hour or so, expecting it to finish the processing, but no, it still occupies a lot of CPU.

**Comment by SkaceKamen** [comment]
Hi, this can happen, usually when there's unexpected combination of macros, but I can't really know where the issue could be without seeing the code.

**Comment by Sparker95** [comment]
That's our code: https://github.com/Sparker95/Project_0/tree/development/Project_0.Altis
The macros amount is big indeed.
Maybe it would be useful to add an output somewhere so that we can understand that the plugin is stuck at some file? Or such an output exists already? I'm sorry, I'm quite new to VS Code.

**Comment by SkaceKamen** [comment]
Well, no there's really no output, these issues shouldn't ever happen. I'll try to find the issue with your project, hopefully it's just a small issue.

**Comment by billw2012** [comment]
Repro:
test.sqf:
```sqf
#include "test.hpp"
```
test.hpp
```c++
#define A(a) (a)
// (A)

```

**Comment by Sparker95** [comment]
So did I break everything with my function-like macros again? :D

**Comment by SkaceKamen** [comment]
Thanks for the repro, I'm really sorry but I don't have much free time right now to look at it, but it will really help when I get to it.

**Comment by billw2012** [comment]
So this was a problem in sqflint project not this one, I have made a pull request in that project that addresses it, along with other preproc issues I found.

**Comment by SkaceKamen** [comment]
Should be solved in 0.9.8, if not, I'll reopen the issue.
Thanks @billw2012.
