### ISSUE TITLE
Feature: Parse .hpp and add functions to global variablel ist

### ISSUE THREAD

**Issue by m1ndst0rm** [SkaceKamen/vscode-sqflint#5]
It would be nice if you could also parse .hpp files and add functions to the function list.
https://community.bistudio.com/wiki/Functions_Library_(Arma_3)

**Comment by SkaceKamen** [comment]
Good idea, I already have HPP parser ready, so it shouldn't be too hard to implement. My only concern is collision with C++ extensions (HPP is also used for c++ header files)

**Comment by SkaceKamen** [comment]
Basic HPP parser implemented in 0.7.0.
