### ISSUE TITLE
CfgFunctions issue with 0.9.8

### ISSUE THREAD

**Issue by Wyqer** [SkaceKamen/vscode-sqflint#51]
Since the update this night all own functions, defined via CfgFunctions.hpp, are marked as possibly undefined variables.

Before the update, same project, it worked fine and also parsed the function header as tooltip.

**Comment by SkaceKamen** [comment]
That's weird, I don't think I've touched the cfgFunctions parser in last update. Could you elaborate how you define your functions?

Do you use macros in your functions definitions or just plain definitions?

**Comment by veteran29** [comment]
All of our functions are included via this file (which itself is included into description.ext):

https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97/Missionframework/KPLIB_functions.hpp

**Comment by SkaceKamen** [comment]
O damn, I've noticed I've pushed old version of the description.ext parser, which could be the issue. Let mi fix that quickly.

**Comment by Wyqer** [comment]
Would be an "easy fix", which is nice ^^

By the way. Am I wrong or was there autocompletion for own global/local variables and functions somewhere in the past? Currently I've only autocompletion for BI commands and nothing else and I'm unsure, if it was always that way.

**Comment by SkaceKamen** [comment]
I've pushed new version, 0.9.81, please try if it works now.

For the autocompletion, it should display everything. If not, there's something wrong, I'll test it.

**Comment by SkaceKamen** [comment]
For the autocompletion, the fix will probably be harder, #52
