### ISSUE TITLE
Multiply symbol(*) followed by function expressions in hpp files is wrongly parsed as uncompleted comments

### ISSUE THREAD

**Issue by GoldJohnKing** [SkaceKamen/vscode-sqflint#57]
Multiply symbol(*) followed by function expressions in hpp files is wrongly parsed as uncompleted comments.

Please see the picture below to have an instant view:
Notice that "value * virable" is correctly parsed, but "virable * (function expression)" is not.
![屏幕截图(14)](https://user-images.githubusercontent.com/26923626/62693577-61355a00-ba05-11e9-99ff-992ac1eee61c.png)

**Comment by SkaceKamen** [comment]
The HPP parser is still very fragile, thanks for reporting this

My next target is to add full support for macros and such, which would probably also fix this, but that will require me to write another parser, which I don't have time for right now 😢
