### ISSUE TITLE
Feature: add preprocessor command #define

### ISSUE THREAD

**Issue by m1ndst0rm** [SkaceKamen/vscode-sqflint#6]
Parsing the function after #define and adding it to the command list.
https://community.bistudio.com/wiki/PreProcessor_Commands#.23define

**Comment by AGPHeaddikilla** [comment]
One more thing: I would appreciate if there would be the #include "path\to\sin.sqf" function.
It also would be greate if there were a $PREFIX$ parser. So you can define an alias for the current absolute path. #include Syntax is available in the link before.

**Comment by SkaceKamen** [comment]
I've already updated parser to support preprocessor commands but I need to spend some time testing it.  Only problem is that I currently need to study for finals, so the update will be available in week or two...

What do you mean by $PREFIX$ parser? Do you mean way to define "/a3_ui" => "C:\extracted\a3_ui" so you can include files with absolute path  (like "/a3_ui/headers.hpp") and still be able to parse them?

**Comment by AGPHeaddikilla** [comment]
I do mean the following:
$PREFIX$ is a file in the main directory of an .pbo-source directory. In this file is an alias (in Arma 3 for the .pbo location) for sqf-lint it is an alias for the absolute path to the source directory itself. I hope this is understandable.
$PREFIX$-File:
`a3\someModuleName\fileInSourceDirectory`

And yeah: In conclusion you are right.
It was just an idea in addtion to #include
Good luck for the finals!

**Comment by SkaceKamen** [comment]
`#define` and `#include` is now integrated (but include only includes preprocesor commands).
I'll move the include prefixes to new task as it's kind of separate issue.
