### ISSUE TITLE
How to click "more info" in the hover infobox

### ISSUE THREAD

**Issue by irvnriir** [SkaceKamen/vscode-sqflint#65]
its probably a vsc question, but i can't find such phrase that search would give anything .

**Comment by RZSenfo** [comment]
I dont get what exactly you are trying to say.
Do you want a more info button in the hoverbox or is the hoverbox not opening?

**Comment by irvnriir** [comment]
When the mouse is moved the box gets closed .
![Screenshot 07-05-2020 16 28 27](https://user-images.githubusercontent.com/13949704/86537171-93cd2880-bedc-11ea-8968-4b1f81876ad4.png)

**Comment by SkaceKamen** [comment]
![image](https://user-images.githubusercontent.com/2076742/102827069-2f4a4b00-43e2-11eb-824f-76a399650e59.png)

Works for me, you just hover over command and then move to the link and click. Either way, that's not really an issue with this extension, but with Visual Studio Code
