### ISSUE TITLE
Feature: Add params & private to local variables

### ISSUE THREAD

**Issue by m1ndst0rm** [SkaceKamen/vscode-sqflint#7]
Would be nice if you could add params & private array to local variables so they aren't highlighted as possibly not-defined.
https://community.bistudio.com/wiki/params
https://community.bistudio.com/wiki/private

**Comment by SkaceKamen** [comment]
Params should already work that way (if not, please provide example where it fails).
Does private actually define the varibles? I tought it only declares variables as private...

**Comment by m1ndst0rm** [comment]
My bad. Apparently after some time (probably saving?) they worked.
