### ISSUE TITLE
String definitions gone wrong

### ISSUE THREAD

**Issue by AGPHeaddikilla** [SkaceKamen/vscode-sqflint#8]
It is just a short noticement. Since I scripted with a "false" string definition. I do not get the main error. Simply because there was no Engine-Type-Error.
The following is the problem:
```sqf
_var = '"'; // not possible
_var = '""' // it have to be quoted
```
I would recommend that you just add quoting of <"> in a string definition with <'> surrounding.
Thanks.

**Comment by AGPHeaddikilla** [comment]
I just tried to reproduce the error: It seems to be fixed.

**Comment by SkaceKamen** [comment]
OK, I've updated the string definition a few times since then, so maybe I fixed it accidentally. Fell free to reopen the issue if you find it's not fixed.
